Repository boostcamp-2020/Project12-B-Slack-Web, pull requests merged in 2020-12, with the labels that each got.

#78 feat: 메시지 컴포넌트 제작
  client/src/components/molecules/GithubLoginButton/GithubLoginButton.stories.tsx
  client/src/components/molecules/Message/Message.stories.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/shared/App.tsx
Labels: FE, 기능추가

#80 feat: Oauth Login 연동
  client/package-lock.json
  client/package.json
  client/src/common/utils/api.ts
  client/src/common/utils/index.ts
  client/src/components/atoms/Button/Button.tsx
  client/src/components/molecules/GithubLoginButton/GithubLoginButton.tsx
  client/src/pages/Chatroom.tsx
  server/package-lock.json
  server/package.json
  server/src/application.ts
  server/src/common/middleware/redis.ts
  server/src/controller/oauth-controller.ts
  server/src/router/oauth.ts
Labels: API, FE, 기능추가

#79 feat: Reply API 구현 (댓글 생성, 단일 조회, 부분 조회 API)
  server/src/controller/reply-controller.ts
  server/src/model/reply.ts
  server/src/router/api.ts
  server/src/router/reply-router.ts
  server/src/service/reply-service.ts
Labels: API, 기능추가

#81 feat: Reaction API 구현 (리액션 생성, 리액션 전체 조회)
  server/src/controller/reaction-controller.ts
  server/src/model/reaction.ts
  server/src/router/api.ts
  server/src/router/reaction-router.ts
  server/src/service/reaction-service.ts
Labels: API, 기능추가

#82 feat: 채팅방 메시지 조회 api 구현
  server/src/controller/message-controller.ts
  server/src/router/message-router.ts
  server/src/service/message-service.ts
Labels: API, 기능추가

#84 feat: 로그인 된 사용자 정보 조회 API 구현 (Auth API)
  server/src/controller/auth-controller.ts
  server/src/controller/oauth-controller.ts
  server/src/router/api.ts
  server/src/router/auth-router.ts
  server/src/service/user-service.ts
Labels: API, 기능추가

#86 feat: 로그인 라우팅 로직 설정 및 Redux 초기 설정
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/src/common/store/index.ts
  client/src/common/store/user-store.ts
  client/src/common/utils/api.ts
  client/src/common/utils/index.ts
  client/src/common/utils/uriParser.ts
  client/src/components/molecules/GithubLoginButton/GithubLoginButton.tsx
  client/src/index.tsx
  client/src/pages/Chatroom.tsx
  client/src/shared/App.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: FE, 기능추가

#87 feat: 채팅방 들어가기 API, 채팅방 초대하기 API 구현
  server/src/controller/user-chatroom-controller.ts
  server/src/router/user-chatroom-router.ts
  server/src/service/user-chatroom-service.ts
Labels: API, 기능추가

#88 feat: CreateChannelModal 구현
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/HoverInput/HoverInput.stories.tsx
  client/src/components/atoms/HoverInput/HoverInput.tsx
  client/src/components/atoms/ModalBox/ModalBox.stories.tsx
  client/src/components/atoms/ModalBox/ModalBox.tsx
  client/src/components/atoms/index.ts
  client/src/components/organisms/CreateChannelModal/CreateChannelModal.stories.tsx
  client/src/components/organisms/CreateChannelModal/CreateChannelModal.tsx
Labels: FE, 기능추가

#89 feat: Header Component 연동
  client/src/common/store/user-store.ts
  client/src/common/utils/api.ts
  client/src/components/molecules/GithubLoginButton/GithubLoginButton.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Header/HeaderContainer.tsx
  client/src/components/organisms/index.ts
  client/src/shared/App.tsx
Labels: FE, 기능추가

#90 feat: 메시지 리액션 추가 API, 메시지 리액션 제거 API 구현
  server/src/controller/message-reaction-controller.ts
  server/src/router/api.ts
  server/src/router/message-reaction-router.ts
  server/src/service/message-reaction-service.ts
Labels: API, 기능추가

#94 feat: 유저 채팅방 조회 API 수정 (자신과의 DM ProfileImg 추가)
  server/src/service/user-chatroom-service.ts
Labels: API, 기능추가

#93 feat: typeORM seed 구현
  server/package-lock.json
  server/package.json
  server/src/seeds/chatroom.ts
Labels: API, 기반설정

#96 feat: user 가입시 defalut channel, dm 배정
  server/src/common/constants/default-section-name.ts
  server/src/model/chatroom.ts
  server/src/service/user-service.ts
Labels: API, 기능추가

#97 feat: Sidebar Redux 적용
  client/.storybook/main.js
  client/src/common/context/index.ts
  client/src/common/dispatch/index.ts
  client/src/common/dispatch/user-chatroom-dispatch.ts
  client/src/common/dispatch/user-dispatch.ts
  client/src/common/store/index.ts
  client/src/common/store/store.ts
  client/src/common/store/user-store.ts
  client/src/common/utils/api.ts
  client/src/common/utils/blockPage.ts
  client/src/common/utils/index.ts
  client/src/common/utils/uriParser.ts
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/Channel/ChannelContainer.tsx
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/DM/DMContainer.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/organisms/Sidebar/SidebarContainer.tsx
  client/src/components/organisms/index.ts
  client/src/shared/App.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: FE, 기능추가

#98 fix: user-service conflict 과정에서 버그 수정
  server/src/service/user-service.ts
Labels: API, 버그수정

#101 feat : 최근 메시지 조회 구현
  server/src/controller/message-controller.ts
  server/src/router/message-router.ts
  server/src/service/message-service.ts
Labels: API, 기능수정, 기능추가

#102 refactor: Front Code refactoring
  .github/PULL_REQUEST_TEMPLATE.md
  client/.storybook/main.js
  client/src/common/dispatch/user-chatroom-dispatch.ts
  client/src/common/dispatch/user-dispatch.ts
  client/src/common/reducer/rootReducer.ts
  client/src/common/reducer/sidebar-reducer.ts
  client/src/common/reducer/user-reducer.ts
  client/src/common/store/index.ts
  client/src/common/store/store.ts
  client/src/common/style/index.ts
  client/src/common/theme/color.ts
  client/src/common/theme/index.ts
  client/src/common/utils/index.ts
  client/src/common/utils/registerToken.ts
  client/src/components/atoms/ActiveLight/ActiveLight.tsx
  client/src/components/atoms/HoverInput/HoverInput.tsx
  client/src/components/atoms/ModalBox/ModalBox.tsx
  client/src/components/atoms/ProfileImg/ProfileImg.tsx
  client/src/components/atoms/Text/Text.tsx
  client/src/components/molecules/ActiveProfileImg/ActiveProfileImg.tsx
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/GithubLoginButton/GithubLoginButton.tsx
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/SendMessageButton/SendMessageButton.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/components/organisms/CreateChannelModal/CreateChannelModal.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Header/HeaderContainer.tsx
  client/src/components/organisms/LoginForm/LoginForm.stories.tsx
  client/src/components/organisms/LoginForm/LoginForm.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/organisms/Sidebar/SidebarContainer.tsx
  client/src/components/organisms/index.ts
  client/src/components/templates/FlexContainer.tsx
  client/src/components/templates/Main.tsx
  client/src/components/templates/MainBox.tsx
  client/src/components/templates/index.ts
  client/src/index.tsx
  client/src/pages/Chatroom.tsx
  client/src/pages/Login.tsx
  client/src/shared/App.tsx
  client/src/theme/color.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: FE, 코드개선

#103 feat: 채널/DM 생성 API 분리
  server/src/common/constants/chat-type.ts
  server/src/common/constants/default-section-name.ts
  server/src/common/constants/http-status-code.ts
  server/src/controller/chatroom-controller.ts
  server/src/model/chatroom.ts
  server/src/router/chatroom-router.ts
  server/src/seeds/chatroom.ts
  server/src/service/chatroom-service.ts
  server/src/service/user-chatroom-service.ts
  server/src/service/user-service.ts
Labels: API, 기능수정, 코드개선

#104 feat: chatroom 정보 연동
  client/src/common/dispatch/chatroom-dispatch.ts
  client/src/common/dispatch/index.ts
  client/src/common/reducer/chatroom-reducer.ts
  client/src/common/reducer/rootReducer.ts
  client/src/common/reducer/sidebar-reducer.ts
  client/src/common/utils/api.ts
  client/src/components/molecules/Channel/ChannelContainer.tsx
  client/src/components/molecules/DM/DMContainer.tsx
  client/src/components/organisms/Header/HeaderContainer.tsx
  client/src/components/organisms/Sidebar/SidebarContainer.tsx
  client/src/pages/Chatroom/Chatroom.tsx
  client/src/pages/Chatroom/ChatroomContainer.tsx
  client/src/pages/index.ts
Labels: FE, 기능추가

#106 feat: Icon 제작 및 HoverIcon Component 구현
  client/public/imgs/detail-icon.png
  client/public/imgs/option-icon.png
  client/public/imgs/plus-icon.png
  client/public/imgs/user-icon.png
  client/src/components/atoms/Icon/Icon.stories.tsx
  client/src/components/molecules/HoverIcon/HoverIcon.stories.tsx
  client/src/components/molecules/HoverIcon/HoverIcon.tsx
Labels: FE, 기능추가

#113 feat: 채팅방 정보 조회 API 수정 (DM 채팅방 title)
  server/src/controller/chatroom-controller.ts
  server/src/service/chatroom-service.ts
Labels: API, 기능수정

#114 fix: 채팅방 초대하기 API 오류 해결
  server/src/service/user-chatroom-service.ts
Labels: 버그수정

#117 feat: chatroom 전체 조회 api 구현
  server/src/controller/chatroom-controller.ts
  server/src/model/chatroom.ts
  server/src/router/chatroom-router.ts
  server/src/service/chatroom-service.ts
  server/src/service/message-service.ts
Labels: API, 기능추가

#119 feat: Browse Page Channel 컴포넌트 제작
  client/src/components/atoms/Text/Text.tsx
  client/src/components/molecules/BrowsePageChannelBody/BrowsePageChannelBody.stories.tsx
  client/src/components/molecules/BrowsePageChannelBody/BrowsePageChannelBody.tsx
  client/src/components/molecules/BrowsePageChannelButton/BrowsePageChannelButton.stories.tsx
  client/src/components/molecules/BrowsePageChannelButton/BrowsePageChannelButton.tsx
  client/src/components/molecules/BrowsePageChannelHeader/BrowsePageChannelHeader.stories.tsx
  client/src/components/molecules/BrowsePageChannelHeader/BrowsePageChannelHeader.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.stories.tsx
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.tsx
  client/src/components/organisms/index.ts
Labels: FE, 기능추가

#120 refactor: React-Redux 구조 변경
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/src/common/dispatch/chatroom-dispatch.ts
  client/src/common/dispatch/index.ts
  client/src/common/dispatch/user-chatroom-dispatch.ts
  client/src/common/dispatch/user-dispatch.ts
  client/src/common/reducer/chatroom-reducer.ts
  client/src/common/reducer/rootReducer.ts
  client/src/common/reducer/sidebar-reducer.ts
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/actions/user-action.ts
  client/src/common/store/index.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/reducers/index.ts
  client/src/common/store/reducers/user-reducer.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/sagas/index.ts
  client/src/common/store/sagas/user-saga.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/store/types/user-types.ts
  client/src/common/utils/api.ts
  client/src/common/utils/index.ts
  client/src/common/utils/registerToken.ts
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/Channel/ChannelContainer.tsx
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/DM/DMContainer.tsx
  client/src/components/molecules/GithubLoginButton/GithubLoginButton.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Header/HeaderContainer.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/organisms/Sidebar/SidebarContainer.tsx
  client/src/components/organisms/index.ts
  client/src/pages/Chatroom/Chatroom.tsx
  client/src/pages/Chatroom/ChatroomContainer.tsx
  client/src/pages/index.ts
  client/src/shared/App.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: FE, 코드개선

#121 feat: ChannelModal Component 구현
  client/src/common/theme/color.ts
  client/src/components/atoms/DropMenuBox/DropMenuBox.stories.tsx
  client/src/components/atoms/DropMenuBox/DropMenuBox.tsx
  client/src/components/atoms/DropMenuItem/DropMenuItem.stories.tsx
  client/src/components/atoms/DropMenuItem/DropMenuItem.tsx
  client/src/components/atoms/index.ts
  client/src/components/molecules/ChannelModal/ChannelModal.stories.tsx
  client/src/components/molecules/ChannelModal/ChannelModal.tsx
  client/src/components/molecules/index.ts
Labels: FE, 기능추가

#122 feat: UserBox component 구현
  client/src/common/theme/color.ts
  client/src/components/molecules/UserBox/UserBox.stories.tsx
  client/src/components/molecules/UserBox/UserBox.tsx
  client/src/components/molecules/index.ts
Labels: FE, 기능추가

#123 feat: Emoji Component 구현
  client/package-lock.json
  client/package.json
  client/src/common/theme/color.ts
  client/src/components/atoms/Emoji/Emoji.stories.tsx
  client/src/components/atoms/Emoji/Emoji.tsx
  client/src/components/atoms/index.ts
  client/src/components/molecules/EmojiBox/EmojiBox.stories.tsx
  client/src/components/molecules/EmojiBox/EmojiBox.tsx
  client/src/components/molecules/index.ts
Labels: FE, 기능추가

#133 feat: Message Reply Bar 제작
  client/src/common/theme/color.ts
  client/src/common/utils/timeAgo.ts
  client/src/components/molecules/MessageReplyBar/MessageReplyBar.stories.tsx
  client/src/components/molecules/MessageReplyBar/MessageReplyBar.tsx
  client/src/components/molecules/index.ts
Labels: FE, 기능추가

#138 fix: merge 과정 index 누락 현상 해결
  client/src/components/atoms/index.ts
Labels: FE, 버그수정

#139 feat: Actionbar 구현
  client/public/imgs/emoji-icon.png
  client/public/imgs/thread-icon.png
  client/src/components/molecules/Actionbar/Actionbar.stories.tsx
  client/src/components/molecules/Actionbar/Actionbar.tsx
  client/src/components/molecules/HoverIcon/HoverIcon.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/index.ts
Labels: FE, 기능추가

#142 feat: socket.io message 관련 기능 구현
  server/package-lock.json
  server/package.json
  server/src/application.ts
  server/src/service/message-service.ts
  server/src/socket/event/connection-event.ts
  server/src/socket/event/message-event.ts
  server/src/socket/handler/chatroom-handler.ts
  server/src/socket/handler/message-handler.ts
  server/src/socket/index.ts
  server/src/socket/init-socket.ts
  server/src/socket/middleware/jwt.ts
  server/src/socket/socket.ts
  server/tsconfig.json
Labels: API, 기능추가

#140 feat: Browse Page Controls 구현
  client/public/imgs/filter-icon.png
  client/public/imgs/sort-icon.png
  client/src/components/molecules/BlackButtonWithIcon/BlackButtonWithIcon.stories.tsx
  client/src/components/molecules/BlackButtonWithIcon/BlackButtonWithIcon.tsx
  client/src/components/molecules/BrowsePageControls/BrowsePageControls.stories.tsx
  client/src/components/molecules/BrowsePageControls/BrowsePageControls.tsx
  client/src/components/molecules/index.ts
Labels: FE, 기능추가

#143 feat: socket reply 구현
  server/src/common/constants/event-name.ts
  server/src/service/message-service.ts
  server/src/service/reply-service.ts
  server/src/socket/event/message-event.ts
  server/src/socket/event/reply-event.ts
  server/src/socket/handler/chatroom-handler.ts
  server/src/socket/handler/message-handler.ts
  server/src/socket/handler/reply-handler.ts
  server/src/socket/index.ts
Labels: API, 기능추가

#146 feat: AddChannelButton 제작
  client/src/components/atoms/DropMenuBox/DropMenuBox.tsx
  client/src/components/atoms/DropMenuItem/DropMenuItem.tsx
  client/src/components/molecules/AddChannelButton/AddChannelButton.stories.tsx
  client/src/components/molecules/AddChannelButton/AddChannelButton.tsx
  client/src/components/molecules/ChannelModal/ChannelModal.tsx
  client/src/components/molecules/HoverIcon/HoverIcon.tsx
  client/src/components/molecules/index.ts
Labels: FE, 기능추가

#145 refactor : 코드리뷰 관련 리팩토링
  server/src/common/constants/event-name.ts
  server/src/service/reply-service.ts
  server/src/socket/event/message-event.ts
  server/src/socket/event/reply-event.ts
  server/src/socket/handler/message-handler.ts
  server/src/socket/handler/reply-handler.ts
  server/src/socket/index.ts
Labels: API, 코드개선

#147 feat: 채팅방 메시지 보내기 소켓 연동
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/src/common/socket/emits/message.ts
  client/src/common/socket/socketIO.ts
  client/src/common/socket/types/message-types.ts
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/store/types/user-types.ts
  client/src/common/utils/api.ts
  client/src/components/atoms/Input/Input.tsx
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/molecules/SendMessageButton/SendMessageButton.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/pages/Chatroom/Chatroom.tsx
  client/tsconfig.json
  client/webpack.config.js
  server/src/router/message-router.ts
  server/src/service/message-service.ts
Labels: API, FE, 기능수정, 기능추가

#151 feat: Modal Store 구현
  client/src/common/store/actions/modal-action.ts
  client/src/common/store/reducers/index.ts
  client/src/common/store/reducers/modal-reducer.ts
  client/src/common/store/types/modal-types.ts
Labels: FE, 기능추가

#148 feat: Section Hover 컴포넌트 제작
  client/.storybook/main.js
  client/src/common/constants/default-section-name.ts
  client/src/common/constants/index.ts
  client/src/components/molecules/AddChannelButton/AddChannelButton.tsx
  client/src/components/molecules/ChannelModal/ChannelModal.tsx
  client/src/components/molecules/Section/Section.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: FE, 기능추가

#152 feat: chatroom 속 컴포넌트 추가 및 메시지 전송 로직 구현
  client/src/components/atoms/Input/Input.tsx
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/molecules/UserBox/UserBox.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/pages/Chatroom/Chatroom.tsx
Labels: FE, 기능추가

#153 feat: 채널 생성 기능 구현
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/utils/api.ts
  client/src/components/atoms/HoverInput/HoverInput.tsx
  client/src/components/atoms/ModalBox/ModalBox.tsx
  client/src/components/molecules/Section/Section.stories.tsx
  client/src/components/organisms/CreateChannelModal/CreateChannelModal.tsx
  client/src/components/organisms/Sidebar/Sidebar.stories.tsx
  client/src/components/organisms/index.ts
  client/src/shared/App.tsx
Labels: FE, 기능추가

#154 feat: logout 기능 구현
  client/.eslintrc.json
  client/src/common/utils/api.ts
  client/src/common/utils/index.ts
  client/src/common/utils/logout.ts
Labels: FE, 기능추가

#155 feat: create channel 비동기 로직 추가
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/utils/api.ts
  client/src/components/organisms/CreateChannelModal/CreateChannelModal.tsx
Labels: FE, 기능수정

#156 fix: 다른 채팅방에서 메시지가 오는 현상 수정 및 logout alert 삭제
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/utils/logout.ts
Labels: FE, 버그수정

#158 feat: sidebar scroll 구현
  client/src/common/store/actions/modal-action.ts
  client/src/common/store/reducers/modal-reducer.ts
  client/src/common/store/types/modal-types.ts
  client/src/components/atoms/DropMenuBox/DropMenuBox.tsx
  client/src/components/molecules/AddChannelButton/AddChannelButton.tsx
  client/src/components/molecules/ChannelModal/ChannelModal.tsx
  client/src/components/organisms/CreateChannelModal/CreateChannelModal.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/templates/Body.tsx
  client/src/components/templates/index.ts
  client/src/shared/App.tsx
Labels: FE, 기능추가

#159 feat: message time 추가
  client/src/common/utils/time.ts
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/MessageReplyBar/MessageReplyBar.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
Labels: FE, 기능추가

#160 feat: Browse Page 검색창 구현
  client/public/imgs/close-filled-icon.png
  client/public/imgs/search-icon.png
  client/src/common/constants/index.ts
  client/src/common/constants/key-code.ts
  client/src/components/atoms/Icon/Icon.stories.tsx
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/Text/Text.tsx
  client/src/components/molecules/BrowsePageSearchBar/BrowsePageSearchBar.stories.tsx
  client/src/components/molecules/BrowsePageSearchBar/BrowsePageSearchBar.tsx
  client/src/components/organisms/BrowsePageHeader/BrowsePageHeader.stories.tsx
  client/src/components/organisms/BrowsePageHeader/BrowsePageHeader.tsx
Labels: FE, 기능추가

#157 feat: Browse Page Header 컴포넌트 구현
  client/src/components/organisms/BrowsePageHeader/BrowsePageHeader.tsx
Labels: FE, 기능추가

#162 feat: Browse Page 관련 컴포넌트 UI 변경
  client/src/components/atoms/Button/Button.tsx
  client/src/components/molecules/BlackButtonWithIcon/BlackButtonWithIcon.stories.tsx
  client/src/components/molecules/BlackButtonWithIcon/BlackButtonWithIcon.tsx
  client/src/components/molecules/BrowsePageChannelBody/BrowsePageChannelBody.tsx
  client/src/components/molecules/BrowsePageChannelButton/BrowsePageChannelButton.tsx
  client/src/components/molecules/BrowsePageControls/BrowsePageControls.tsx
  client/src/components/molecules/WhiteButtonWithIcon/WhiteButtonWithIcon.stories.tsx
  client/src/components/molecules/WhiteButtonWithIcon/WhiteButtonWithIcon.tsx
  client/src/components/molecules/index.ts
Labels: FE, 기능추가

#163 feat: infinite scroll 구현
  client/src/common/constants/chatroom-event-type.ts
  client/src/common/constants/index.ts
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/utils/api.ts
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  server/src/service/message-service.ts
Labels: FE, 기능추가

#165 feat: socket chatroom join 이벤트 추가
  server/src/common/constants/event-name.ts
  server/src/socket/event/chatroom-event.ts
  server/src/socket/event/connection-event.ts
  server/src/socket/handler/chatroom-handler.ts
  server/src/socket/index.ts
Labels: API, 기능추가

#167 bugfix: week 4 배포 간 bug 수정
  client/src/common/utils/auth.ts
  client/src/common/utils/blockPage.ts
  client/src/common/utils/index.ts
  client/src/common/utils/registerToken.ts
  client/src/common/utils/uriParser.ts
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/UserBox/UserBox.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/pages/LoginLoading.tsx
  client/src/pages/index.ts
  client/src/shared/App.tsx
Labels: FE, 버그수정

#168 feat : chatroom pagination api 구현
  server/src/controller/chatroom-controller.ts
  server/src/router/chatroom-router.ts
  server/src/service/chatroom-service.ts
  server/src/socket/event/chatroom-event.ts
Labels: API, 기능수정, 기능추가

#170 feat: messages 조회 api 쿼리스트링으로 수정 및 리팩토링
  server/src/controller/message-controller.ts
  server/src/router/message-router.ts
  server/src/service/message-service.ts
Labels: API, 기능수정, 기능추가, 코드개선

#171 feat: UserBoxModal 구현
  client/src/common/store/actions/modal-action.ts
  client/src/common/store/reducers/modal-reducer.ts
  client/src/common/store/types/modal-types.ts
  client/src/components/molecules/UserBox/UserBox.tsx
  client/src/components/molecules/UserBoxModalSearchBar/UserBoxModalSearchBar.stories.tsx
  client/src/components/molecules/UserBoxModalSearchBar/UserBoxModalSearchBar.tsx
  client/src/components/molecules/UserBoxModalUserItem/UserBoxModalUserItem.stories.tsx
  client/src/components/molecules/UserBoxModalUserItem/UserBoxModalUserItem.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/UserBoxModal/UserBoxModal.stories.tsx
  client/src/components/organisms/UserBoxModal/UserBoxModal.tsx
  client/src/components/organisms/index.ts
  client/src/shared/App.tsx
Labels: FE, 기능추가

#172 feat: Browse Page 라우팅 및 화면 구성
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/components/molecules/BrowsePageControls/BrowsePageControls.stories.tsx
  client/src/components/molecules/BrowsePageControls/BrowsePageControls.tsx
  client/src/components/molecules/BrowsePageSearchBar/BrowsePageSearchBar.tsx
  client/src/components/molecules/ChannelModal/ChannelModal.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.tsx
  client/src/components/organisms/BrowsePageHeader/BrowsePageHeader.tsx
  client/src/components/organisms/index.ts
  client/src/components/templates/Body.tsx
  client/src/pages/ChannelBrowser/ChannelBrowser.tsx
  client/src/pages/Chatroom/Chatroom.tsx
  client/src/pages/index.ts
  client/src/shared/App.tsx
Labels: FE, 기능추가

#173 fix: 무한 스크롤 버그 및 Chatroom 정보 500 에러 해결
  client/src/common/utils/api.ts
  client/src/pages/Chatroom/Chatroom.tsx
Labels: FE, 버그수정

#177 feat: Thread Page 생성
  client/src/common/utils/uriParser.ts
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/pages/Chatroom/Chatroom.tsx
  client/src/pages/Chatroom/ChatroomThread.tsx
  client/src/pages/Chatroom/Thread.tsx
  client/src/pages/index.ts
  client/src/shared/App.tsx
Labels: FE, 기능추가

#176 feat: Channel Store 구현
  client/src/common/store/actions/channel-action.ts
  client/src/common/store/reducers/channel-reducer.ts
  client/src/common/store/reducers/index.ts
  client/src/common/store/sagas/channel-saga.ts
  client/src/common/store/sagas/index.ts
  client/src/common/store/types/channel-types.ts
  client/src/common/utils/api.ts
Labels: FE, 기능추가

#178 fix: page index 누락 수정
  client/src/pages/index.ts
Labels: FE, 버그수정

#180 chore: webpack 브라우저 캐싱 설정
  client/webpack.config.js
Labels: FE, 버그수정

#181 배포 서버 브라우저 캐싱 적용
  client/webpack.config.js
Labels: FE, 기능추가

#183 feat: Browse Page 채널 목록 구현
  client/src/components/molecules/BrowsePageChannelBody/BrowsePageChannelBody.stories.tsx
  client/src/components/molecules/BrowsePageChannelBody/BrowsePageChannelBody.tsx
  client/src/components/molecules/BrowsePageChannelHeader/BrowsePageChannelHeader.stories.tsx
  client/src/components/molecules/BrowsePageChannelHeader/BrowsePageChannelHeader.tsx
  client/src/components/molecules/BrowsePageControls/BrowsePageControls.tsx
  client/src/components/molecules/BrowsePageSearchBar/BrowsePageSearchBar.tsx
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.stories.tsx
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.tsx
  client/src/components/organisms/BrowsePageChannelList/BrowsePageChannelList.stories.tsx
  client/src/components/organisms/BrowsePageChannelList/BrowsePageChannelList.tsx
  client/src/components/organisms/index.ts
  client/src/pages/ChannelBrowser/ChannelBrowser.tsx
Labels: FE, 기능추가

#182 feat: 전체 chatroom 조회에 isJoined 프로퍼티, 헤더에 채널 전체 갯수 추가 구현
  server/src/controller/chatroom-controller.ts
  server/src/service/chatroom-service.ts
Labels: API, 기능수정, 기능추가, 버그수정

#184 feat: 채널 생성 시 join chatroom 로직 추가 (socket)
  client/src/common/store/sagas/chatroom-saga.ts
Labels: FE, 기능추가

#185 feat: Browse Page 채널 목록 구현(Infinite Scroll 구현, 채널 Join 기능 구현)
  client/.eslintrc.json
  client/src/common/socket/emits/chatroom.ts
  client/src/common/socket/types/chatroom-types.ts
  client/src/common/store/actions/channel-action.ts
  client/src/common/store/reducers/channel-reducer.ts
  client/src/common/store/sagas/channel-saga.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/channel-types.ts
  client/src/common/utils/api.ts
  client/src/components/atoms/Button/Button.tsx
  client/src/components/molecules/BrowsePageChannelButton/BrowsePageChannelButton.tsx
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.stories.tsx
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.tsx
  client/src/components/organisms/BrowsePageChannelList/BrowsePageChannelList.stories.tsx
  client/src/components/organisms/BrowsePageChannelList/BrowsePageChannelList.tsx
  server/src/controller/chatroom-controller.ts
  server/src/service/chatroom-service.ts
Labels: FE, 기능추가

#186 Release Browse Page
  client/.eslintrc.json
  client/src/common/socket/emits/chatroom.ts
  client/src/common/socket/types/chatroom-types.ts
  client/src/common/store/actions/channel-action.ts
  client/src/common/store/reducers/channel-reducer.ts
  client/src/common/store/sagas/channel-saga.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/channel-types.ts
  client/src/common/utils/api.ts
  client/src/components/atoms/Button/Button.tsx
  client/src/components/molecules/BrowsePageChannelBody/BrowsePageChannelBody.stories.tsx
  client/src/components/molecules/BrowsePageChannelBody/BrowsePageChannelBody.tsx
  client/src/components/molecules/BrowsePageChannelButton/BrowsePageChannelButton.tsx
  client/src/components/molecules/BrowsePageChannelHeader/BrowsePageChannelHeader.stories.tsx
  client/src/components/molecules/BrowsePageChannelHeader/BrowsePageChannelHeader.tsx
  client/src/components/molecules/BrowsePageControls/BrowsePageControls.tsx
  client/src/components/molecules/BrowsePageSearchBar/BrowsePageSearchBar.tsx
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.stories.tsx
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.tsx
  client/src/components/organisms/BrowsePageChannelList/BrowsePageChannelList.stories.tsx
  client/src/components/organisms/BrowsePageChannelList/BrowsePageChannelList.tsx
  client/src/components/organisms/index.ts
  client/src/pages/ChannelBrowser/ChannelBrowser.tsx
  server/src/controller/chatroom-controller.ts
  server/src/service/chatroom-service.ts
Labels: API, FE

#187 feat: Thread layout 설정
  client/public/imgs/close-icon.png
  client/src/components/molecules/Actionbar/Actionbar.stories.tsx
  client/src/components/molecules/Actionbar/Actionbar.tsx
  client/src/components/molecules/HoverIcon/HoverIcon.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/organisms/ThreadHeader/ThreadHeader.tsx
  client/src/components/organisms/index.ts
  client/src/components/templates/Main.tsx
  client/src/components/templates/MainBox.tsx
  client/src/pages/Chatroom/Chatroom.tsx
  client/src/pages/Chatroom/ChatroomThread.tsx
  client/src/pages/Chatroom/Thread.tsx
  client/src/shared/App.tsx
Labels: FE, 기능추가

#188 feat: messageId를 이용한 replies 조회 api 구현
  server/src/controller/reply-controller.ts
  server/src/model/reaction.ts
  server/src/router/reply-router.ts
  server/src/service/message-service.ts
  server/src/service/reaction-service.ts
  server/src/service/reply-service.ts
Labels: API, 기능수정, 기능추가

#191 feat: 채널 생성, 채널 join시 채팅방으로 이동하는 동작 구현
  client/src/common/socket/emits/chatroom.ts
  client/src/common/socket/types/chatroom-types.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/sagas/channel-saga.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.tsx
Labels: FE, 기능추가

#189 feat: Profile Modal 컴포넌트 구현
  client/src/components/atoms/ProfileModalBody/ProfileModalBody.stories.tsx
  client/src/components/atoms/ProfileModalBody/ProfileModalBody.tsx
  client/src/components/atoms/ProfileModalImg/ProfileModalImg.stories.tsx
  client/src/components/atoms/ProfileModalImg/ProfileModalImg.tsx
  client/src/components/atoms/index.ts
  client/src/components/molecules/ProfileModal/ProfileModal.stories.tsx
  client/src/components/molecules/ProfileModal/ProfileModal.tsx
  client/src/components/molecules/index.ts
Labels: FE, 기능추가

#190 feat: Thread Page 연동
  client/src/common/socket/emits/thread.ts
  client/src/common/socket/types/thread-types.ts
  client/src/common/store/actions/thread-action.ts
  client/src/common/store/reducers/index.ts
  client/src/common/store/reducers/thread-reducer.ts
  client/src/common/store/sagas/index.ts
  client/src/common/store/sagas/thread-saga.ts
  client/src/common/store/types/thread-types.ts
  client/src/common/utils/api.ts
  client/src/components/molecules/Actionbar/Actionbar.tsx
  client/src/components/molecules/InputReply/InputReply.stories.tsx
  client/src/components/molecules/InputReply/InputReply.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/MessageReplyBar/MessageReplyBar.tsx
  client/src/components/molecules/Reply/Reply.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/ThreadBody/ThreadBody.tsx
  client/src/components/organisms/ThreadBody/ThreadReplies.tsx
  client/src/components/organisms/index.ts
  client/src/components/templates/Body.tsx
  client/src/pages/Chatroom/Chatroom.tsx
  client/src/pages/Chatroom/ChatroomThread.tsx
  client/src/pages/Chatroom/Thread.tsx
  server/src/socket/handler/reply-handler.ts
Labels: FE, 기능추가

#192 feat: message reaction socket 구현
  server/src/common/constants/event-name.ts
  server/src/controller/message-reaction-controller.ts
  server/src/controller/reaction-controller.ts
  server/src/model/reaction.ts
  server/src/service/message-reaction-service.ts
  server/src/service/message-service.ts
  server/src/service/reaction-service.ts
  server/src/service/reply-service.ts
  server/src/socket/event/message-reaction-event.ts
  server/src/socket/handler/message-reaction-handler.ts
  server/src/socket/handler/reply-handler.ts
  server/src/socket/index.ts
Labels: API, 기능수정, 기능추가

#193 feat: Create Channel Button 동작 구현 및 Scroll 문제 해결
  client/src/components/organisms/BrowsePageChannelList/BrowsePageChannelList.tsx
  client/src/pages/ChannelBrowser/ChannelBrowser.tsx
Labels: FE, 기능수정, 기능추가

#195 Fix/message socket fix reply
  server/src/service/message-service.ts
Labels: API, 버그수정

#196 feat: Thread Profile 중복 제거 및 useEffect 설정
  client/src/components/molecules/MessageReplyBar/MessageReplyBar.tsx
  client/src/components/organisms/ThreadBody/ThreadBody.tsx
Labels: FE, 기능추가

#197 feat: message reply image uri 중복 제거 구현
  server/src/service/message-service.ts
Labels: API, 기능추가

#199 fix: get messages 버그 수정
  server/src/service/message-service.ts
Labels: API, 버그수정

#198 feat: Thread 댓글 작성 시 Chatroom 반영
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/store/types/message-reactions-type.ts
  client/src/common/store/types/message-types.ts
  client/src/components/molecules/InputReply/InputReply.tsx
  client/src/components/molecules/MessageReplyBar/MessageReplyBar.tsx
  client/src/components/organisms/ThreadHeader/ThreadHeader.tsx
  client/src/components/templates/Body.tsx
Labels: FE, 기능추가

#200 feat: replycount 구현
  server/src/controller/reply-controller.ts
  server/src/service/reply-service.ts
Labels: API, 기능추가

#201 fix: message가 빈 컨텐츠로 오는 오류 해결
  client/src/common/store/types/message-types.ts
  client/src/components/templates/Body.tsx
Labels: FE, 버그수정

#202 fix: lastReplyAt 동작 버그 수정
  server/src/service/message-service.ts
Labels: API, 버그수정

#203 feat: Profile Modal 동작 구현 (Open/Close)
  client/src/common/store/actions/modal-action.ts
  client/src/common/store/reducers/modal-reducer.ts
  client/src/common/store/types/modal-types.ts
  client/src/components/atoms/DropMenuBox/DropMenuBox.tsx
  client/src/components/atoms/Text/Text.tsx
  client/src/components/molecules/ChannelModal/ChannelModal.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/ProfileModal/ProfileModal.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/shared/App.tsx
Labels: FE, 기능추가

#204 feat: thread infinite Scroll 구현
  client/src/common/constants/index.ts
  client/src/common/constants/scroll-event-type.ts
  client/src/common/store/actions/thread-action.ts
  client/src/common/store/reducers/thread-reducer.ts
  client/src/common/store/sagas/thread-saga.ts
  client/src/common/store/types/thread-types.ts
  client/src/common/utils/api.ts
  client/src/common/utils/scroll.ts
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/molecules/InputReply/InputReply.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/ThreadBody/ThreadBody.tsx
Labels: FE, 기능추가

#205 fix: 마우스가 화면을 벗어날 경우 Profile Modal Close
  client/src/components/templates/Body.tsx
Labels: FE, 기능수정

#206 feat: delete message reaction socket 구현
  server/src/service/message-reaction-service.ts
  server/src/service/reply-service.ts
  server/src/socket/event/message-reaction-event.ts
  server/src/socket/handler/message-reaction-handler.ts
Labels: API, 기능수정, 기능추가

#208 feat: join DM socket 구현
  server/src/common/constants/event-name.ts
  server/src/model/socket.ts
  server/src/model/user.ts
  server/src/repository/socket-repository.ts
  server/src/service/socket-service.ts
  server/src/socket/event/chatroom-event.ts
  server/src/socket/event/connection-event.ts
  server/src/socket/event/disconnect-event.ts
  server/src/socket/handler/chatroom-handler.ts
  server/src/socket/handler/socket-handler.ts
  server/src/socket/index.ts
Labels: API, 기능추가

#209 feat: chatroom 단일 조회시 DM이면 ProfileUri를 추가해서 전달 구현
  server/src/service/chatroom-service.ts
Labels: API, 기능수정

#210 feat: Profile Modal을 통한 DM 생성 기능 구현
  client/src/common/constants/chat-type.ts
  client/src/common/constants/index.ts
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/utils/api.ts
  client/src/components/molecules/ProfileModal/ProfileModal.tsx
Labels: FE, 기능추가

#211 fix: 자신과의 DM 프로필 버그 수정
  server/src/service/chatroom-service.ts
Labels: API, 버그수정

#212 feat: join DM 기능 구현 (socket을 통한 상대측 채팅방 생성)
  client/src/common/socket/emits/chatroom.ts
  client/src/common/socket/types/chatroom-types.ts
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/components/templates/Body.tsx
Labels: FE, 기능추가

#213 feat: Reply 컴포넌트에 Profile Modal Open 동작 추가
  client/src/common/utils/modal.ts
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/Reply/Reply.tsx
Labels: FE, 기능추가

#214 feat: websocket으로 사용할 수 있도록 인증 방법 변경
  client/src/common/socket/socketIO.ts
  server/src/socket/middleware/jwt.ts
Labels: API, 기능수정

#215 feat: leave chatroom 구현
  server/src/common/constants/event-name.ts
  server/src/service/user-chatroom-service.ts
  server/src/socket/event/chatroom-event.ts
  server/src/socket/handler/chatroom-handler.ts
Labels: API, 기능추가

#216 feat: Message Emoji 생성 / 조회 / 삭제 구현
  client/package-lock.json
  client/package.json
  client/src/common/socket/emits/reaction.ts
  client/src/common/socket/types/reaction-types.ts
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/actions/modal-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/reducers/modal-reducer.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/store/types/message-reactions-type.ts
  client/src/common/store/types/modal-types.ts
  client/src/components/atoms/Emoji/Emoji.stories.tsx
  client/src/components/atoms/Emoji/Emoji.tsx
  client/src/components/molecules/Actionbar/Actionbar.tsx
  client/src/components/molecules/EmojiBox/EmojiBox.stories.tsx
  client/src/components/molecules/EmojiBox/EmojiBox.tsx
  client/src/components/molecules/EmojiPicker/EmojiPicker.stories.tsx
  client/src/components/molecules/EmojiPicker/EmojiPicker.tsx
  client/src/components/molecules/HoverIcon/HoverIcon.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/templates/Body.tsx
  client/src/shared/App.tsx
  server/src/service/message-service.ts
Labels: FE, 기능추가

#217 feat: 채팅방 떠나기 기능 구현 (Browse Page)
  client/src/common/socket/emits/chatroom.ts
  client/src/common/socket/types/chatroom-types.ts
  client/src/common/store/actions/channel-action.ts
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/channel-reducer.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/types/channel-types.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.tsx
  client/src/components/templates/Body.tsx
  server/src/service/chatroom-service.ts
Labels: FE, 기능추가

#218 fix: typeORM 속성 크기 변경
  server/src/model/reaction.ts
Labels: API, 버그수정

#219 fix: message reaction, leave chatroom deletedAt관련 문제 수정
  server/src/service/chatroom-service.ts
  server/src/service/message-reaction-service.ts
  server/src/service/user-chatroom-service.ts
Labels: API, 기능수정, 버그수정

#220 feat: UserBoxModal에 ProfileModal Open 동작 추가
  client/src/components/molecules/ProfileModal/ProfileModal.tsx
  client/src/components/molecules/UserBoxModalUserItem/UserBoxModalUserItem.stories.tsx
  client/src/components/molecules/UserBoxModalUserItem/UserBoxModalUserItem.tsx
  client/src/components/organisms/UserBoxModal/UserBoxModal.stories.tsx
  client/src/components/organisms/UserBoxModal/UserBoxModal.tsx
Labels: FE, 기능추가

#221 feat: reply reaction socket 구현
  server/src/common/constants/event-name.ts
  server/src/service/reply-reaction-service.ts
  server/src/socket/event/reply-rection-event.ts
  server/src/socket/handler/reply-reaction-handler.ts
  server/src/socket/index.ts
Labels: API, 기능추가

#222 feat: chatroom 권한 조회 구현
  server/src/controller/chatroom-controller.ts
  server/src/service/user-chatroom-service.ts
Labels: API, 기능추가

#225 fix: lightHouse를 통한 코드 개선
  client/public/imgs/channel-icon.png
  client/public/imgs/lock-icon.png
  client/public/index.html
  client/src/common/theme/color.ts
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/LogoImg/LogoImg.tsx
  client/src/components/atoms/ProfileImg/ProfileImg.tsx
  client/src/components/molecules/Message/Message.tsx
Labels: FE, 코드개선

#226 fix: URL을 통해 본인이 속해있지 않은 채팅방에 접근 가능한 문제 해결
  client/src/common/constants/http-status-code.ts
  client/src/common/constants/index.ts
  client/src/common/utils/api.ts
Labels: FE, 버그수정

#227 fix: Leave Chatroom 랜더링 문제 해결
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/channel-reducer.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.tsx
  client/src/components/templates/Body.tsx
Labels: FE, 버그수정

#229 feat: Reply Reaction 생성 / 삭제 구현
  client/src/common/constants/chat-type.ts
  client/src/common/constants/chatroom-type.ts
  client/src/common/constants/index.ts
  client/src/common/socket/emits/reaction.ts
  client/src/common/socket/types/reaction-types.ts
  client/src/common/store/actions/thread-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/reducers/modal-reducer.ts
  client/src/common/store/reducers/thread-reducer.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/message-types.ts
  client/src/common/store/types/modal-types.ts
  client/src/common/store/types/reactions-type.ts
  client/src/common/store/types/thread-types.ts
  client/src/components/molecules/Actionbar/Actionbar.stories.tsx
  client/src/components/molecules/Actionbar/Actionbar.tsx
  client/src/components/molecules/EmojiBox/EmojiBox.tsx
  client/src/components/molecules/EmojiPicker/EmojiPicker.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/Reply/Reply.tsx
  client/src/components/organisms/ThreadBody/ThreadBody.tsx
  client/src/components/templates/Body.tsx
  server/src/socket/handler/reply-reaction-handler.ts
Labels: FE, 기능추가

#230 Release Reply Reaction
  client/src/common/constants/chat-type.ts
  client/src/common/constants/chatroom-type.ts
  client/src/common/constants/index.ts
  client/src/common/socket/emits/reaction.ts
  client/src/common/socket/types/reaction-types.ts
  client/src/common/store/actions/thread-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/reducers/modal-reducer.ts
  client/src/common/store/reducers/thread-reducer.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/types/message-types.ts
  client/src/common/store/types/modal-types.ts
  client/src/common/store/types/reactions-type.ts
  client/src/common/store/types/thread-types.ts
  client/src/components/molecules/Actionbar/Actionbar.stories.tsx
  client/src/components/molecules/Actionbar/Actionbar.tsx
  client/src/components/molecules/EmojiBox/EmojiBox.tsx
  client/src/components/molecules/EmojiPicker/EmojiPicker.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/Reply/Reply.tsx
  client/src/components/organisms/ThreadBody/ThreadBody.tsx
  client/src/components/templates/Body.tsx
  server/src/socket/handler/reply-reaction-handler.ts
Labels: API, FE

#231 fix: Chatroom Layout 및 CSS 변경
  client/src/components/molecules/MessageReplyBar/MessageReplyBar.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/templates/Main.tsx
  client/src/pages/Chatroom/Chatroom.tsx
  client/src/pages/Chatroom/ChatroomThread.tsx
  client/src/pages/Chatroom/Thread.tsx
Labels: FE, 기능수정

#232 fix: Thread Open 상태에서 채팅방 이동 문제 해결
  client/src/common/store/reducers/thread-reducer.ts
  client/src/common/store/sagas/thread-saga.ts
  client/src/common/store/types/thread-types.ts
  client/src/common/utils/uriParser.ts
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/organisms/ThreadHeader/ThreadHeader.tsx
  client/src/pages/Chatroom/Chatroom.tsx
  client/src/pages/Chatroom/ChatroomThread.tsx
Labels: FE, 버그수정

#233 fix: 긴 채널 이름 생략 처리, DM Section 채널 추가 버튼 삭제
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/Text/Text.tsx
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/Section/Section.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/organisms/ThreadHeader/ThreadHeader.tsx
  client/src/components/templates/Body.tsx
Labels: FE, 기능수정

#234 refactor: constants 코딩 컨벤션 통일 및 컴포넌트의 size string을 constants로 대체
  client/src/common/constants/chat-type.ts
  client/src/common/constants/chatroom-type.ts
  client/src/common/constants/default-section-name.ts
  client/src/common/constants/http-status-code.ts
  client/src/common/constants/index.ts
  client/src/common/constants/key-code.ts
  client/src/common/constants/scroll-event-type.ts
  client/src/common/constants/size.ts
  client/src/common/constants/sort-method.ts
  client/src/components/atoms/ActiveLight/ActiveLight.stories.tsx
  client/src/components/atoms/ActiveLight/ActiveLight.tsx
  client/src/components/atoms/Icon/Icon.stories.tsx
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/LogoImg/LogoImg.tsx
  client/src/components/atoms/ProfileImg/ProfileImg.stories.tsx
  client/src/components/atoms/ProfileImg/ProfileImg.tsx
  client/src/components/atoms/ProfileModalBody/ProfileModalBody.tsx
  client/src/components/atoms/Text/Text.tsx
  client/src/components/molecules/Actionbar/Actionbar.tsx
  client/src/components/molecules/ActiveProfileImg/ActiveProfileImg.stories.tsx
  client/src/components/molecules/ActiveProfileImg/ActiveProfileImg.tsx
  client/src/components/molecules/AddChannelButton/AddChannelButton.tsx
  client/src/components/molecules/BrowsePageChannelBody/BrowsePageChannelBody.tsx
  client/src/components/molecules/BrowsePageChannelHeader/BrowsePageChannelHeader.tsx
  client/src/components/molecules/BrowsePageControls/BrowsePageControls.tsx
  client/src/components/molecules/BrowsePageSearchBar/BrowsePageSearchBar.tsx
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/GithubLoginButton/GithubLoginButton.tsx
  client/src/components/molecules/HoverIcon/HoverIcon.stories.tsx
  client/src/components/molecules/HoverIcon/HoverIcon.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/MessageReplyBar/MessageReplyBar.tsx
  client/src/components/molecules/Reply/Reply.tsx
  client/src/components/molecules/SendMessageButton/SendMessageButton.tsx
  client/src/components/molecules/UserBoxModalSearchBar/UserBoxModalSearchBar.tsx
  client/src/components/molecules/UserBoxModalUserItem/UserBoxModalUserItem.tsx
  client/src/components/molecules/WhiteButtonWithIcon/WhiteButtonWithIcon.tsx
  client/src/components/organisms/BrowsePageHeader/BrowsePageHeader.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/components/organisms/CreateChannelModal/CreateChannelModal.tsx
  client/src/components/organisms/LoginForm/LoginForm.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/organisms/ThreadHeader/ThreadHeader.tsx
  client/src/components/organisms/UserBoxModal/UserBoxModal.tsx
Labels: FE, 코드개선

#235 fix: 채팅방/DM 이동 문제 해결
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/DM/DM.tsx
Labels: FE, 버그수정

#237 feat: 채팅방 join시 다른 사용자의 채팅방 정보 최신화
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/components/templates/Body.tsx
Labels: FE, 기능추가

#238 feat: infinite Scroll에 throttle 적용
  client/package-lock.json
  client/package.json
  client/src/common/constants/scroll-event-type.ts
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/ThreadBody/ThreadBody.tsx
Labels: FE, 기능추가

#239 docs: Update README.md
  README.md
  client/README.md
Labels: 문서작업

#240 fix: message, thread Input ID 설정
  client/src/components/atoms/Input/Input.stories.tsx
  client/src/components/atoms/Input/Input.tsx
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/molecules/InputReply/InputReply.tsx
Labels: FE, 버그수정

#241 chore: image Size 조절
  client/public/imgs/close-icon.png
  client/public/imgs/detail-icon.png
  client/public/imgs/emoji-icon.png
  client/public/imgs/lock-icon.png
  client/public/imgs/logo-text.png
  client/public/imgs/send-message-icon.png
  client/public/imgs/star-blue.png
  client/public/imgs/star.png
  client/public/imgs/thread-icon.png
  client/public/imgs/user-icon.png
Labels: FE

#242 fix: hidden Label 설정
  client/src/components/atoms/Input/Input.tsx
Labels: FE

#245 refactor: styled-components <any>태그 삭제
  client/src/components/molecules/Actionbar/Actionbar.tsx
  client/src/components/molecules/AddChannelButton/AddChannelButton.tsx
  client/src/components/molecules/BrowsePageChannelBody/BrowsePageChannelBody.tsx
  client/src/components/molecules/BrowsePageChannelHeader/BrowsePageChannelHeader.tsx
  client/src/components/molecules/BrowsePageControls/BrowsePageControls.tsx
  client/src/components/molecules/BrowsePageSearchBar/BrowsePageSearchBar.tsx
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/EmojiBox/EmojiBox.tsx
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/molecules/InputReply/InputReply.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/MessageReplyBar/MessageReplyBar.tsx
  client/src/components/molecules/Reply/Reply.tsx
  client/src/components/molecules/Section/Section.tsx
  client/src/components/molecules/SendMessageButton/SendMessageButton.tsx
  client/src/components/molecules/UserBox/UserBox.tsx
  client/src/components/molecules/UserBoxModalSearchBar/UserBoxModalSearchBar.tsx
  client/src/components/molecules/UserBoxModalUserItem/UserBoxModalUserItem.tsx
  client/src/components/molecules/WhiteButtonWithIcon/WhiteButtonWithIcon.tsx
  client/src/components/organisms/BrowsePageChannel/BrowsePageChannel.tsx
  client/src/components/organisms/BrowsePageChannelList/BrowsePageChannelList.tsx
  client/src/components/organisms/BrowsePageHeader/BrowsePageHeader.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/organisms/ThreadBody/ThreadReplies.tsx
  client/src/components/organisms/UserBoxModal/UserBoxModal.tsx
  client/src/pages/ChannelBrowser/ChannelBrowser.tsx
  client/src/pages/Chatroom/ChatroomThread.tsx
  client/src/pages/Chatroom/Thread.tsx
Labels: FE, 코드개선

#244 refactor: store type 정의
  client/src/common/store/actions/channel-action.ts
  client/src/common/store/actions/chatroom-action.ts
  client/src/common/store/actions/modal-action.ts
  client/src/common/store/actions/thread-action.ts
  client/src/common/store/reducers/channel-reducer.ts
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/reducers/modal-reducer.ts
  client/src/common/store/reducers/thread-reducer.ts
  client/src/common/store/reducers/user-reducer.ts
  client/src/common/store/sagas/channel-saga.ts
  client/src/common/store/sagas/chatroom-saga.ts
  client/src/common/store/sagas/thread-saga.ts
  client/src/common/store/types/channel-types.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/store/types/message-types.ts
  client/src/common/store/types/modal-types.ts
  client/src/common/store/types/reactions-type.ts
  client/src/common/store/types/thread-types.ts
  client/src/common/store/types/user-types.ts
  client/src/common/utils/uriParser.ts
  client/src/components/molecules/Actionbar/Actionbar.tsx
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/molecules/Message/Message.tsx
  client/src/components/molecules/Section/Section.stories.tsx
  client/src/components/organisms/BrowsePageChannelList/BrowsePageChannelList.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/Sidebar/Sidebar.stories.tsx
  client/src/components/organisms/ThreadBody/ThreadBody.tsx
  client/src/components/templates/Body.tsx
  client/src/pages/Chatroom/Chatroom.tsx
  client/src/pages/Chatroom/Thread.tsx
Labels: FE, 코드개선

#246 refactor: Store Type 네이밍 통일
  client/src/common/store/reducers/chatroom-reducer.ts
  client/src/common/store/types/channel-types.ts
  client/src/common/store/types/chatroom-types.ts
  client/src/common/store/types/message-types.ts
  client/src/common/store/types/thread-types.ts
Labels: FE, 코드개선

#247 fix: 채팅방/DM 이동 문제 해결
  client/src/common/utils/uriParser.ts
  client/src/components/organisms/ThreadBody/ThreadBody.tsx
  client/src/pages/Chatroom/Thread.tsx
Labels: FE, 버그수정
