Repository boostcamp-2020/Project12-B-Slack-Web, pull requests merged in 2020-11, with the labels that each got.

#4 docs: README.md 및 Issue, PR 템플릿 업로드
  .github/ISSUE_TEMPLATE/bug_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 기반설정

#5 chore: Webpack, Babel, ESLint 설정 및 기본 폴더 구조 생성
  .gitignore
  client/.babelrc.json
  client/.eslintrc.json
  client/.prettierrc.json
  client/env/.env.sample
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/imgs/logo-text.png
  client/public/imgs/logo.png
  client/public/index.html
  client/src/common/context/index.ts
  client/src/common/style/index.ts
  client/src/common/utils/index.ts
  client/src/components/atoms/index.ts
  client/src/components/molecules/index.ts
  client/src/components/organisms/index.ts
  client/src/components/templates/index.ts
  client/src/index.tsx
  client/src/pages/index.ts
  client/src/shared/App.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: 기반설정

#8 chore: 서버 개발 환경 설정
  server/.env.sample
  server/.eslintrc.js
  server/.prettierrc
  server/docker-compose.yml
  server/ormconfig.js
  server/package-lock.json
  server/package.json
  server/src/application.ts
  server/src/common/utils/index.ts
  server/src/controller/index.ts
  server/src/model/index.ts
  server/src/repository/index.ts
  server/src/router/index.ts
  server/src/service/index.ts
  server/tsconfig.json
Labels: 기반설정

#48 feat: StoryBook 적용
  client/.eslintrc.json
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Button/Button.css
  client/src/components/atoms/Button/Button.stories.tsx
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/index.ts
Labels: 기능추가, 기반설정

#49 feat: icon component 제작
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/public/imgs/index.d.ts
  client/src/components/atoms/Icon/Icon.stories.tsx
  client/src/components/atoms/Icon/Icon.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: 기능추가, 버그수정

#50 feat: TypeORM 모델 생성
  server/package-lock.json
  server/package.json
  server/src/model/chatroom.ts
  server/src/model/index.ts
  server/src/model/message.ts
  server/src/model/section.ts
  server/src/model/user-chatroom.ts
  server/src/model/user.ts
  server/src/repository/chatroom-repository.ts
  server/src/repository/index.ts
  server/src/repository/message-repository.ts
  server/src/repository/section-repository.ts
  server/src/repository/user-chatroom-repository.ts
  server/src/repository/user-repository.ts
Labels: 기능추가, 기반설정

#53 feat: Header 컴포넌트 제작
  client/src/components/atoms/ActiveLight/ActiveLight.stories.tsx
  client/src/components/atoms/ActiveLight/ActiveLight.tsx
  client/src/components/atoms/Button/Button.css
  client/src/components/atoms/Button/Button.stories.tsx
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/ProfileImg/ProfileImg.stories.tsx
  client/src/components/atoms/ProfileImg/ProfileImg.tsx
  client/src/components/atoms/index.ts
  client/src/components/molecules/ActiveProfileImg/ActiveProfileImg.stories.tsx
  client/src/components/molecules/ActiveProfileImg/ActiveProfileImg.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/Header/Header.stories.tsx
  client/src/components/organisms/Header/Header.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: 기능추가

#52 feat: TypeORM 설정 추가
  server/.eslintrc.js
  server/package-lock.json
  server/package.json
  server/src/application.ts
Labels: 기반설정

#55 feat: User API 구현 (모든 유저 조회 API, 단일 유저 조회 API)
  server/.eslintrc.js
  server/src/application.ts
  server/src/common/constants/http-status-code.ts
  server/src/common/error/bad-request-error.ts
  server/src/common/error/conflict-error.ts
  server/src/common/error/forbidden-error.ts
  server/src/common/error/not-found-error.ts
  server/src/common/error/unauthorized-error.ts
  server/src/common/middleware/error-handler.ts
  server/src/controller/user-controller.ts
  server/src/router/index.ts
  server/src/router/user-router.ts
  server/src/service/user-service.ts
  server/tsconfig.json
Labels: 기능추가

#57 feat: Sidebar component 구현
  client/public/imgs/channel-icon.png
  client/public/imgs/lock-icon.png
  client/src/components/atoms/Icon/Icon.stories.tsx
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/Text/Text.stories.tsx
  client/src/components/atoms/Text/Text.tsx
  client/src/components/atoms/index.ts
  client/src/components/molecules/Channel/Channel.stories.tsx
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/DM/DM.stories.tsx
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/Section/Section.stories.tsx
  client/src/components/molecules/Section/Section.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/Sidebar/Sidebar.stories.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/organisms/index.ts
  client/src/theme/color.ts
  client/src/theme/index.ts
Labels: 기능추가

#59 refactor: Sidebar component 페이지 적용
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/ProfileImg/ProfileImg.tsx
  client/src/components/molecules/ActiveProfileImg/ActiveProfileImg.tsx
  client/src/components/molecules/Channel/Channel.tsx
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/Section/Section.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/pages/Chatroom.tsx
  client/src/pages/Login.tsx
  client/src/pages/index.ts
  client/src/shared/App.tsx
  client/webpack.config.js
Labels: 코드개선

#58 feat: JWT 관련 기능 구현
  server/package-lock.json
  server/package.json
  server/src/application.ts
  server/src/common/config/passport.ts
  server/src/controller/oauth-controller.ts
  server/src/model/user.ts
  server/src/router/api/oauth.ts
  server/src/router/index.ts
  server/src/service/user-service.ts
  server/tsconfig.json
Labels: API, 기능추가, 코드개선

#62 feat: 채널/DM 생성 API 구현
  server/.eslintrc.js
  server/src/common/utils/validator.ts
  server/src/controller/chatroom-controller.ts
  server/src/controller/oauth-controller.ts
  server/src/model/chatroom.ts
  server/src/repository/chatroom-repository.ts
  server/src/router/chatroom-router.ts
  server/src/router/index.ts
  server/src/service/chatroom-service.ts
Labels: 기능추가

#63 feat: chatRoom component 구현
  client/public/imgs/send-message-icon.png
  client/public/imgs/star-blue.png
  client/public/imgs/star.png
  client/public/index.html
  client/src/components/atoms/Icon/Icon.stories.tsx
  client/src/components/atoms/Input/Input.stories.tsx
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/ProfileImg/ProfileImg.tsx
  client/src/components/atoms/Text/Text.tsx
  client/src/components/atoms/index.ts
  client/src/components/molecules/DM/DM.tsx
  client/src/components/molecules/InputMessage/InputMessage.stories.tsx
  client/src/components/molecules/InputMessage/InputMessage.tsx
  client/src/components/molecules/SendMessageButton/SendMessageButton.stories.tsx
  client/src/components/molecules/SendMessageButton/SendMessageButton.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/ChatroomBody/ChatroomBody.stories.tsx
  client/src/components/organisms/ChatroomBody/ChatroomBody.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.stories.tsx
  client/src/components/organisms/ChatroomHeader/ChatroomHeader.tsx
  client/src/components/organisms/Header/Header.tsx
  client/src/components/organisms/Sidebar/Sidebar.tsx
  client/src/components/organisms/index.ts
  client/src/pages/Chatroom.tsx
  client/src/shared/App.tsx
Labels: 기능추가

#64 feat: 유저 채팅방 조회 API 구현 및 Router 리팩토링
  server/package-lock.json
  server/package.json
  server/src/controller/index.ts
  server/src/controller/user-chatroom-controller.ts
  server/src/router/api.ts
  server/src/router/chatroom-router.ts
  server/src/router/index.ts
  server/src/router/oauth.ts
  server/src/router/user-chatroom-router.ts
  server/src/service/index.ts
  server/src/service/user-chatroom-service.ts
Labels: 기능추가, 코드개선

#67 feat: Login page 뷰 구현
  client/src/components/atoms/Button/Button.stories.tsx
  client/src/components/atoms/Button/Button.tsx
  client/src/components/atoms/LogoImg/LogoImg.stories.tsx
  client/src/components/atoms/LogoImg/LogoImg.tsx
  client/src/components/atoms/Text/Text.stories.tsx
  client/src/components/atoms/Text/Text.tsx
  client/src/components/atoms/index.ts
  client/src/components/molecules/GithubLoginButton/GithubLoginButton.stories.tsx
  client/src/components/molecules/GithubLoginButton/GithubLoginButton.tsx
  client/src/components/molecules/index.ts
  client/src/components/organisms/Header/Header.tsx
  client/src/components/templates/FlexContainer.tsx
  client/src/components/templates/index.ts
  client/src/pages/Login.tsx
Labels: FE, 기능추가

#68 feat: message api 구현
  server/package-lock.json
  server/package.json
  server/src/application.ts
  server/src/controller/message-controller.ts
  server/src/controller/oauth-controller.ts
  server/src/router/api.ts
  server/src/router/api/oauth.ts
  server/src/router/index.ts
  server/src/router/message-router.ts
  server/src/service/message-service.ts
Labels: API, 기능추가

#71 feat: jwt 인증을 쿠키에서 헤더로 변경
  server/src/common/config/passport.ts
  server/src/controller/oauth-controller.ts
  server/src/router/api/oauth.ts
Labels: API, 기능수정

#72 feat: 채팅방 API 구현 (정보 조회, 정보 변경, 삭제 API)
  server/src/controller/chatroom-controller.ts
  server/src/router/chatroom-router.ts
  server/src/service/chatroom-service.ts
Labels: API, 기능추가

#76 feat: TypeORM 모델 생성 (reply, reply-reaction)
  server/src/model/message.ts
  server/src/model/reaction.ts
  server/src/model/reply-reaction.ts
  server/src/model/reply.ts
  server/src/model/user.ts
  server/src/repository/reply-reaction-repository.ts
  server/src/repository/reply-repository.ts
Labels: 기반설정

#77 fix: TypeORM model import 오류 해결
  server/src/model/message.ts
  server/src/model/reaction.ts
  server/src/model/user.ts
Labels: 버그수정
